detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - e
  UtilityFunction:
    exclude:
      - FixtureHelpers#read_fixture

exclude_paths:
  - vendor/
