inherit_from:
  - https://rubocop.jgarber.cc/rubocop.yml
  - https://rubocop.jgarber.cc/rubocop-rspec.yml

plugins: rubocop-packaging

AllCops:
  TargetRubyVersion: "2.7"

# Checks that spec file paths are consistent and well-formed.
RSpec/SpecFilePathFormat:
  CustomTransform:
    IndieWeb: "indieweb"
