plugins:
  - dryer_lint
  - dryer_lint-rspec
  - rubocop-packaging

# Checks that spec file paths are consistent and well-formed.
RSpec/SpecFilePathFormat:
  CustomTransform:
    IndieWeb: "indieweb"
