inherit_from:
  - https://raw.githubusercontent.com/jgarber623/rubocop-configs/main/.rubocop.gem.yml

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/FilePath:
  CustomTransform:
    IndieWeb: indieweb
